In [40]:
2.6 * 0

0.0

### Exercise 07.1

Create two very long NumPy arrays `x` and `y` and sum the arrays using:

1. The NumPy addition syntax, `z = x + y`;
2. A `for` loop that computes the sum entry-by-entry

Compare the time requred for the two approaches for vectors of different lenghts. The values of the array entries are not import for this test.

*Hint*: To loop over an array using indeces, try a construction like:

```
x = np.ones(100)
y = np.ones(len(x))
for i in range(len(x)):
    print(x[i] * y[i])
```

In [11]:
import numpy as np

In [44]:
x = np.random.rand(10000, 10000)

In [46]:
y = np.random.rand(10000, 10000)

In [47]:
%time z = x + y

CPU times: user 420 ms, sys: 1.74 s, total: 2.16 s
Wall time: 3.19 s


In [48]:
def compute_sum(x, y):
    z = np.zeros(x.shape)
    for i in range(z.shape[0]):
        for j in range(z.shape[1]):
            z[i,j] = x[i,j] + y[i, j]
    return z

In [50]:
%time z = compute_sum(x, y)

CPU times: user 1min 12s, sys: 3.73 s, total: 1min 16s
Wall time: 1min 28s


### Exercise 07.2

Anonymised scores (out of 60) for an examination are stored in a NumPy array. Write:

- A function that takes a NumPy array of the raw scores and returns the scores as a percentage sorted from lowest to highest (try using `scores.sort()`, where scores in a NumPy array holding the scores).



In [1]:
import numpy as np

In [2]:
def sorted_scores(scores, total):
    """Returns a sorted percentage of grades."""
    scores_sorted = (np.array(scores) / total * 100)
    scores_sorted.sort()
    return scores_sorted

In [3]:
scores =[89, 90, 56, 78, 93, 43, 67, 78, 68, 94, 89]

In [4]:
print(sorted_scores(scores, 120))

[ 35.83333333  46.66666667  55.83333333  56.66666667  65.          65.
  74.16666667  74.16666667  75.          77.5         78.33333333]


- A function that returns the maximum, minimum and mean of the raw scores as a dictionary with the keys 'min', 'max', and 'mean'. Use the NumPy array functions `min()`, and `mean()` to do the computation, e.g. `max = scores.max()`.

In [5]:
scores = sorted_scores(scores, 120)

In [6]:
type(scores)

numpy.ndarray

In [7]:
def statistics(scores):
    stats = {}
    stats['min'] = scores.min()
    stats['max'] = scores.max()
    stats['mean'] = scores.mean()
    return stats

In [8]:
statistics(scores)

{'max': 78.333333333333329,
 'mean': 64.015151515151516,
 'min': 35.833333333333336}

- Modify your function for the min, max, and mean to optionally exclude the highest and lowest scores from the computation of the min, max and mean. *Hint*: sort the array of scores and use array sclicing to exclude the first and the last entries.

In [9]:
def stats2(scores):
    scores.sort()
    scores = scores[1:-1]
    stats = {}
    stats['min'] = scores.min()
    stats['max'] = scores.max()
    stats['mean'] = scores.mean()
    return stats

In [10]:
stats2(scores)

{'max': 77.5, 'mean': 65.555555555555557, 'min': 46.666666666666664}

### Exercise 07.3

for the two-dimensional array:

In [51]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])

In [52]:
print(A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


use array slicing to 

- Extract the third column as a 1D array

In [53]:
A[:,2]

array([  -2.43,   54.7 ,    3.64, -113.2 ])

- Extract the first two rows as a 2D sub-array

In [54]:
A[:2,]

array([[  4.  ,   7.  ,  -2.43,  67.1 ],
       [ -4.  ,  64.  ,  54.7 ,  -3.33]])

- Extract the bottom-right $2$ x $2$ block as a 2D sub-array

In [55]:
A[2:, 2:]

array([[   3.64,    4.11],
       [-113.2 ,  323.22]])

- Sum the last column

In [61]:
A[:,3]#.sum()

array([  67.1 ,   -3.33,    4.11,  323.22])

In [62]:
A[:,3].sum()

391.10000000000002

In [63]:
A.T

array([[   4.  ,   -4.  ,    2.43,    1.2 ],
       [   7.  ,   64.  ,   23.2 ,    2.5 ],
       [  -2.43,   54.7 ,    3.64, -113.2 ],
       [  67.1 ,   -3.33,    4.11,  323.22]])

In [64]:
A

array([[   4.  ,    7.  ,   -2.43,   67.1 ],
       [  -4.  ,   64.  ,   54.7 ,   -3.33],
       [   2.43,   23.2 ,    3.64,    4.11],
       [   1.2 ,    2.5 , -113.2 ,  323.22]])

### Exercise 07.4

In a previous exercise, you implemented the bisection algorithm to find approximate roots of a mathematical function. Use the SciPy bisection function `optimize.bisect` to find roots of the mathematical function that was used in the previous exercise. Compare the results computed by SciPy and your program form the earlier exercise, and compare the computational time (using %time).

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.bisect.html